In [2]:
import numpy as np

row_vec = np.array([1,2,3])
col_vec = np.array([[1],[2],[3]])

Question 1

In [10]:
print("Row vector:", row_vec)

Row vector: [1 2 3]


Question 2

In [12]:
print("Column Vector:\n", col_vec)

Column Vector:
 [[1]
 [2]
 [3]]


Question 3

In [18]:
three_by_three = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a.)", three_by_three)
print("\nb.)", three_by_three[1,1])
print("\nc.)", three_by_three[:2,:])
print("\nd.)", three_by_three[2,:])
print("\ne.)", three_by_three[:,2])

a.) [[1 2 3]
 [4 5 6]
 [7 8 9]]

b.) 5

c.) [[1 2 3]
 [4 5 6]]

d.) [7 8 9]

e.) [3 6 9]
