In [1]:
import numpy as np

Question 1

In [20]:
A = np.ones((4,5))
print("A =", A)
B = np.zeros((4,5))
print("\nB =", B)
print("\nData type of A:", A.dtype)

A = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

B = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Data type of A: float64


Question 2

In [11]:
C = A[:2,-3:]
print("New array C:\n", C)

D = B[:2,-3:].copy()
print("\nNew array D:\n", D)

New array C:
 [[1. 1. 1.]
 [1. 1. 1.]]

New array D:
 [[0. 0. 0.]
 [0. 0. 0.]]


Question 3

In [21]:
D[D == 0] = -1
print("D with replaced values:\n", D)

D with replaced values:
 [[-1. -1. -1.]
 [-1. -1. -1.]]


Question 4

In [23]:
E = C.reshape((3,2))
print("E with reshape:\n", E)
F = E.T
print("F, transpose of E:\n", F)

E with reshape:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
F, transpose of E:
 [[1. 1. 1.]
 [1. 1. 1.]]


Question 5